# Automatically generates a default-deny-all NetworkPolicy in every new namespace.

apiVersion: policies.kyverno.io/v1
kind: GeneratingPolicy
metadata:
  name: default-networkpolicy
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']
        operations: ['CREATE']
        resources: ['namespaces']

  matchConditions:
    - name: exclude-system-namespaces
      expression: >-
        !(object.metadata.name in ['kube-system', 'kube-public', 'kube-node-lease',
        'argocd', 'kyverno', 'falco', 'sealed-secrets',
        'calico-system', 'calico-apiserver', 'tigera-operator',
        'kyverno-templates'])

  variables:
    - name: targetNs
      expression: 'object.metadata.name'
    - name: template
      expression: >-
        resource.Get("networking.k8s.io/v1", "networkpolicies",
                     "kyverno-templates", "default-deny-all")

  evaluation:
    synchronize:
      # Keep generated NetworkPolicies in sync with the template.
      enabled: true

  generate:
    - expression: generator.Apply(variables.targetNs, [variables.template])
