---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: default
spec:
  encryptedData:
    password: AgBXHqEuow4pyg2DjJYptasKPlLLJ/V5egf0NVHz3iz2pEnbatZ+lK4hMqzQRIiGG1501/hIebmIL1sDwyWtNK5FH+6zTCtz9lpVPDUnS78/h0uHuSK/CiK+MBl0nXANv4KcNfoAV+Iqune2nhsJAKUSMSqR7jNt7qGMlx/D5sCm/fj49Svs4+UrGy8wDPnd+f/ySnIXPu00n+SXoBxFncuj5M0d70x/V6VzgN2lojqng4CS2n8ET3VaEiXXrtVx2JeAS2OwgnXG6JHQNxv3JLPnxI5SD3t+oGHu7UKvRIYWRQHxiyhLhlm4A0ZRyf+lh4L0iZyQ9E7P555hWsHLIcTI9I8dmtilG7FtcvFyME36EeXXRPybOC1sLw7JL2AszVawV/gQRH9yu7Ch0tIk90NM7UA/IjRLE9WhWWgiA0+lS/6RjOHX93NNXtsLEahQ6oxsfxfRd12RZV1YzrgcoGPhoOBSNM4yLZ2lUb4/aEyYSh9C5gJ2mV3xwyPwjcpuaxVSOeKuIi5aEUeVtQdJLgM5ADiFiivxg+xA0CO6P8tEkcQn2YszMlemtCGeS9+jMBNtfxHfMGcrqhhx4P3i83am0wHvXMjwhzc/F/kOkhJYjwvj9n61GH8nxqxPc/lFEVeA2lauJm1+3759+jiFajXmrRcorDvsPzZHG4HzfeuLYkvgOM3BFWEjEIU9mixCaH17CfHIo21jMHsQc7d0Gw==
  template:
    metadata:
      name: demo-secret
      namespace: default
