### add-resource-limits: inject default CPU/memory limits when not specified ###
apiVersion: policies.kyverno.io/v1
kind: MutatingPolicy
metadata:
  name: add-resource-limits
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: [v1]
        operations: [CREATE]
        resources: [pods]
  matchConditions:
    - name: exclude-infra-namespaces
      expression: >-
        !(object.metadata.namespace in ['kube-system', 'kube-public', 'kube-node-lease',
        'argocd', 'kyverno', 'falco', 'sealed-secrets',
        'calico-system', 'calico-apiserver', 'tigera-operator'])
  mutations:
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: |
          Object{
            spec: Object.spec{
              containers: object.spec.containers.map(c, Object.spec.containers{
                name: c.name,
                resources: Object.spec.containers.resources{
                  limits: {
                    "cpu": "100m",
                    "memory": "256Mi"
                  }
                }
              })
            }
          }
