### add-default-securitycontext: inject runAsNonRoot, readOnlyRootFilesystem, allowPrivilegeEscalation=false when securityContext is missing ####
apiVersion: policies.kyverno.io/v1
kind: MutatingPolicy
metadata:
  name: add-default-securitycontext
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: [v1]
        operations: [CREATE]
        resources: [pods]
  mutations:
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: |
          Object{
            spec: Object.spec{
              securityContext: Object.spec.securityContext{
                seccompProfile: Object.spec.securityContext.seccompProfile{
                  type: "RuntimeDefault"
                }
              },
              containers: object.spec.containers.map(c, Object.spec.containers{
                name: c.name,
                securityContext: Object.spec.containers.securityContext{
                  runAsNonRoot: true,
                  readOnlyRootFilesystem: true,
                  allowPrivilegeEscalation: false,
                  privileged: false,
                  capabilities: Object.spec.containers.securityContext.capabilities{
                    drop: ["ALL"]
                  },
                  seccompProfile: Object.spec.containers.securityContext.seccompProfile{
                    type: "RuntimeDefault"
                  }
                }
              })
            }
          }
