apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: security-hardening
  sources:
    - repoURL: 'https://kyverno.github.io/kyverno/'
      chart:  kyverno
      targetRevision: 3.3.7
      helm:
        valueFiles:
          - values.yaml
        values: |-
          cleanupController:
            enabled: false
          webhooksCleanup:
            enabled: false
          policyReportsCleanup:
            enabled: false
    - repoURL: 'https://github.com/ghofranehad/k8s-security.git'
      targetRevision: HEAD
      path: kyverno/policies
      directory:
        recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kyverno
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
