apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  project: security-hardening
  source:
      repoURL: https://github.com/ghofranehad/k8s-security.git
      path: argocd/apps
      targetRevision: HEAD
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated: 
      enabled: true
    syncOptions:
      - CreateNamespace=true
