apiVersion: v1
kind: Namespace
metadata:
  name: kyverno-templates
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: kyverno-templates
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
